### ISSUE TITLE
Not Working

### ISSUE THREAD

**Issue by stomarver** [fzzyhmstrs/sns#1]
Minecraft not crashing, mod is installed and shown in mod menu, but new symbols in not visible (i'll check it through keybind menu). For test i remove all mods except sns and libs, and as well doesn't working
![image](https://github.com/user-attachments/assets/fd7ee064-6ddf-465c-a893-43f506547bcc)
maybe i want install additional resource pack or...?

**Comment by stomarver** [comment]
p.s
mc version is 1.21.1
fabric - 0.16.3
fabric api - 0.103.0

(sowwy, english is not my main lang)

**Comment by fzzyhmstrs** [comment]
Symbols and Stuff doesn't automatically change any text in-game. It's a library for another mod to do that. So Keybind Fix (or some other mod) would have to update the vanilla keybind visuals. currently that's not done.
